"""missing Venue fields implemented

Revision ID: a9233783b3b6
Revises: 784034b962d4
Create Date: 2022-05-30 00:47:56.105577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9233783b3b6'
down_revision = '784034b962d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venues', 'seeking_talent')
    op.drop_column('Venues', 'website')
    op.drop_column('Venues', 'genres')
    op.drop_column('Venues', 'seeking_description')
    # ### end Alembic commands ###
